#ifndef ERRORMESSAGE_PRJ_H_INCLUDED
#define ERRORMESSAGE_PRJ_H_INCLUDED

#define ERROR_BUF_SIZE 16

#define ERROR_MESSAGE_LIST \
   ERROR_MESSAGE_ENTRY(COMPRESSOR_TIMEOUT,    ERROR_DISPLAY) \
   ERROR_MESSAGE_ENTRY(COMPRESSOR_FAULT,      ERROR_STOP) \
   ERROR_MESSAGE_ENTRY(REFRIGERANT_HIGHP,     ERROR_DISPLAY) \
   ERROR_MESSAGE_ENTRY(REFRIGERANT_LOWP,      ERROR_DISPLAY) \
   ERROR_MESSAGE_ENTRY(PRESSURE_SENSOR_FAULT, ERROR_DISPLAY) \
   ERROR_MESSAGE_ENTRY(TEMP_SENSOR_FAULT,     ERROR_DISPLAY) \
   ERROR_MESSAGE_ENTRY(COOLANT_LOW,           ERROR_DISPLAY) \
   ERROR_MESSAGE_ENTRY(PUMP_BATTERY_FAULT,    ERROR_STOP) \
   ERROR_MESSAGE_ENTRY(PUMP_POWERTRAIN_FAULT, ERROR_STOP) \
   ERROR_MESSAGE_ENTRY(OCTOVALVE_FAULT,       ERROR_DISPLAY) \

#endif // ERRORMESSAGE_PRJ_H_INCLUDED
